name: stop-devouch

on:
  workflow_dispatch:

jobs:

  stop:
    name: Stop Devouch
    runs-on: ubuntu-latest
    steps:
    - name: Stop Devouch
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USERNAME }}
        key: ${{ secrets.STAGING_PRIVATE_KEY }}
        port: 22
        script: | 
          cd $HOME/DeVouch-BE
          docker compose stop devouch squid-db
          docker compose rm -f -v devouch squid-db
          docker volume prune -f
